# Cargar las funciones internas de Flutter para iOS
podfile_properties = {};
def parse_KV_file(file_path, hash)
  if File.exist?(file_path)
    File.readlines(file_path).each do |line|
      key, value = line.strip.split('=', 2)
      hash[key] = value if key && value
    end
  end
end

parse_KV_file('./Flutter/Generated.xcconfig', podfile_properties)

# Requerir el helper script oficial de Flutter
framework_dir = File.expand_path(File.join('..', 'Flutter'), __FILE__)
require File.join(framework_dir, 'podhelper.rb')

platform :ios, '15.5'
project 'Runner.xcodeproj'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end