platform :ios, '15.5'

# Desactivar la búsqueda automática de workspaces para evitar conflictos
workspace 'Runner.xcworkspace'
project 'Runner.xcodeproj'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Importar manualmente los plugins de Flutter requeridos
  pod 'google_mlkit_commons', :path => '.symlinks/plugins/google_mlkit_commons/ios'
  pod 'google_mlkit_text_recognition', :path => '.symlinks/plugins/google_mlkit_text_recognition/ios'
  pod 'image_picker_ios', :path => '.symlinks/plugins/image_picker_ios/ios'
  pod 'permission_handler_apple', :path => '.symlinks/plugins/permission_handler_apple/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
